'use client';
import type { Treatment } from '../../../types';
import { Card, Field, PageTitle, DataTable } from '../../ui';

type Monitoring={risk_monitoring_id:string;risk_treatment_id:string;monitoring_date:string;monitoring_review?:string|null;actual_risk?:string|null;trend?:string|null;risk_code?:string|null;risk_description?:string; treatment_plan:string;target_residual_risk?:string|null;organization_name?:string};

export default function MonitoringReviuPage({treatments,data,form,setForm,create,canReview,canActual}:{treatments:Treatment[];data:Monitoring[];form:any;setForm:(x:any)=>void;create:()=>void;canReview:boolean;canActual:boolean}){
 return <section><PageTitle icon="bi-clipboard2-pulse" title="Monitoring & Reviu" subtitle="Pemantauan pelaksanaan perlakuan risiko dan reviu actual risk sesuai User Requirement."/><div className="grid-2"><Card title="Input Monitoring & Reviu"><form onSubmit={e=>{e.preventDefault();create()}}><Field label="Perlakuan Risiko"><select required value={form.risk_treatment_id} onChange={e=>setForm({...form,risk_treatment_id:e.target.value})}><option value="">Pilih perlakuan risiko</option>{treatments.map(t=><option key={t.risk_treatment_id} value={t.risk_treatment_id}>{t.treatment_plan}</option>)}</select></Field><Field label="Tanggal Monitoring"><input type="date" required value={form.monitoring_date} onChange={e=>setForm({...form,monitoring_date:e.target.value})}/></Field>{canReview&&<Field label="Monitoring & Reviu"><textarea required={canReview&&!canActual} value={form.monitoring_review} onChange={e=>setForm({...form,monitoring_review:e.target.value})} placeholder="Diisi oleh Manajer Risiko"/></Field>}{canActual&&<Field label="Nilai Actual Risk"><input required={!canReview} value={form.actual_risk} onChange={e=>setForm({...form,actual_risk:e.target.value})} placeholder="Diisi oleh Bidang Pengelolaan Kinerja dan Risiko"/></Field>}<button className="btn-primary">Simpan Monitoring & Reviu</button></form></Card><Card title="Riwayat Monitoring"><DataTable headers={['Risiko','Perlakuan','Tanggal','Reviu','Actual Risk','Trends']} rows={data.map(m=>[m.risk_code||'—',m.treatment_plan,m.monitoring_date,m.monitoring_review||'—',m.actual_risk||'—',m.trend==='DECREASE'?'Menurun':m.trend==='INCREASE'?'Meningkat':m.trend==='STABLE'?'Tetap':'—'])}/></Card></div></section>
}
