export type Org={organization_id:string;organization_name:string;parent_id?:string|null;organization_level?:string|null;is_active?:boolean};
export type Ref={risk_category_id:string;code:string;name:string};
export type StrategicObjective={strategic_objective_id:string;code?:string;name:string};
export type Context={risk_context_id:string;organization_id:string;organization_name?:string;business_process_id?:string|null;business_process_name?:string|null;performance_iku_id?:string|null;performance_iku_name?:string|null;performance_iku_code?:string|null;performance_agreement_id?:string|null;performance_output_manual_id?:string|null;performance_output_name?:string|null;strategic_objective_name?:string|null;activity_objective_id?:string|null;activity_objective_name?:string|null;activity_indicator_id?:string|null;indicator_name?:string|null;output_id?:string|null;output_name?:string|null;external_context?:string|null;internal_context?:string|null;output_detail?:string|null;business_process_detail?:string|null;rejection_reason?:string|null;status:string};
export type RiskReferences={performance_ikus:Array<{iku_id:string;code?:string;indicator_name:string;strategic_objective_name?:string;year:number;organization_id:string;organization_name?:string}>;performance_pks:Array<{agreement_id:string;iku_id:string;year:number;organization_id:string;indicator_name?:string;strategic_objective_name?:string}>;performance_outputs:Array<{output_manual_id:string;code?:string;name:string;year:number;organization_id:string;target_value?:number;unit?:string}>;activity_objectives:Array<{activity_objective_id:string;code?:string;name:string;description?:string}>;activity_indicators:Array<{activity_indicator_id:string;activity_objective_id:string;indicator_code?:string;indicator_name:string;target_value?:number;unit?:string}>;outputs:Array<{output_id:string;code?:string;name:string;target_value?:number;unit?:string}>;business_processes:Array<{business_process_id:string;code?:string;name:string;level?:number}>;risk_categories:Ref[];employees:Array<{employee_id:string;employee_number?:string;employee_name:string;position_name?:string;organization_id:string;organization_name?:string}>};
export type Assessment={risk_assessment_id:string;risk_context_id:string;risk_code?:string;risk_description:string;risk_category_name?:string;inherent_risk?:string;current_risk?:string;risk_level?:string;status:string};
export type Treatment={risk_treatment_id:string;risk_assessment_id:string;treatment_plan:string;treatment_index?:number;target_residual_risk?:string;status:string};
export type Iku={iku_id:string;organization_id:string;organization_name?:string;data_provider_org_name?:string;data_validator_org_name?:string;year:number;strategic_objective_id?:string;strategic_objective_name?:string;indicator_name:string;indicator_description?:string;formula?:string;measurement_unit?:string;data_provider_org_id?:string;data_source?:string;data_validator_org_id?:string;missing_data_action?:string;period_consolidation:string;cascading_type:string;location_consolidation:string;polarization:string;reporting_period:string;renja_type?:string;target_annual?:number;bidang_validation_status?:string;bidang_rejection_reason?:string; pimpinan_validation_status?:string;pimpinan_rejection_reason?:string;active?:boolean;target_tw1?:number;target_tw2?:number;target_tw3?:number;target_tw4?:number;manual_iku_status:string};
export type Pk={agreement_id:string;organization_id:string;organization_name?:string;year:number;iku_id:string;indicator_name?:string;strategic_objective_name?:string;target_tw1?:number;target_tw2?:number;target_tw3?:number;target_tw4?:number;perjanjian_kinerja_status:string};
export type UserRole={role_code:string;role_name:string;organization_id?:string};
export type AuthUser={user_id:string;username:string;employee_name:string;position_name?:string;organization_id:string;organization_name:string;roles:UserRole[]};
export type Output={output_manual_id:string;organization_id:string;organization_name?:string;year:number;classification_code?:string;output_name:string;output_indicator?:string;output_type:string;target_value?:number;unit?:string;component?:string;status:string};

export type AdminRole={role_id:string;role_code:string;role_name:string;description?:string};
export type AdminUser={user_id:string;username:string;is_active:boolean;employee_id:string;employee_number:string;employee_name:string;position_name?:string;email?:string;organization_id:string;organization_name:string;roles:AdminRole[]};
