-- SIMONIK - 005_runtime_privileges.sql
-- Jalankan sebagai database owner/postgres setelah 001-003.
-- Memberikan hak runtime kepada role aplikasi yang digunakan BE (default: simonik).

GRANT USAGE ON SCHEMA master, planning, performance, risk, system TO simonik;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA master, planning, performance, risk, system TO simonik;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA master, planning, performance, risk, system TO simonik;

ALTER DEFAULT PRIVILEGES IN SCHEMA master GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA planning GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA performance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA risk GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA system GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO simonik;

ALTER DEFAULT PRIVILEGES IN SCHEMA master GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA planning GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA performance GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA risk GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO simonik;
ALTER DEFAULT PRIVILEGES IN SCHEMA system GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO simonik;
