'use client';
import { useState } from 'react';
import type { AuthUser } from '../../../types';
import { Card, Field, PageTitle } from '../../ui';

export default function AccountPage({user,api,setUser}:{user:AuthUser;api:<T>(path:string,options?:RequestInit)=>Promise<T>;setUser:(u:AuthUser)=>void}){
 const [form,setForm]=useState({current_password:'',new_password:'',confirm_password:''});const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const save=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');setError('');if(form.new_password!==form.confirm_password){setError('Konfirmasi password baru tidak sama.');return}setSaving(true);try{await api('/auth/password',{method:'PUT',body:JSON.stringify({current_password:form.current_password,new_password:form.new_password})});setMessage('Password berhasil diperbarui.');setForm({current_password:'',new_password:'',confirm_password:''})}catch(e){setError(e instanceof Error?e.message:'Gagal memperbarui password')}finally{setSaving(false)}};
 return <section><PageTitle icon="bi-person-gear" title="Akun Saya" subtitle="Kelola informasi akun dan perbarui password Anda."/><div className="grid-2"><Card title="Informasi Pengguna"><div className="account-info"><b>{user.employee_name}</b><span>{user.username}</span><span>{user.position_name||'—'}</span><span>{user.organization_name}</span><span>{user.roles.map(r=>r.role_name).join(', ')}</span></div></Card><Card title="Ubah Password"><form onSubmit={save}><Field label="Password Saat Ini"><input type="password" required autoComplete="current-password" value={form.current_password} onChange={e=>setForm({...form,current_password:e.target.value})}/></Field><Field label="Password Baru"><input type="password" required minLength={8} autoComplete="new-password" value={form.new_password} onChange={e=>setForm({...form,new_password:e.target.value})}/></Field><Field label="Konfirmasi Password Baru"><input type="password" required minLength={8} autoComplete="new-password" value={form.confirm_password} onChange={e=>setForm({...form,confirm_password:e.target.value})}/></Field>{error&&<div className="login-error"><i className="bi bi-exclamation-circle"/> {error}</div>}{message&&<div className="success-note"><i className="bi bi-check-circle"/> {message}</div>}<button className="btn-primary" disabled={saving}>{saving?'Menyimpan…':'Perbarui Password'}</button></form></Card></div></section>
}
