import type { ReactNode } from 'react';

export function PageTitle({icon,title,subtitle}:{icon:string;title:string;subtitle:string}){return <div className="page-title"><div className="title-icon"><i className={`bi ${icon}`}/></div><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
export function Card({title,children}:{title:string;children:ReactNode}){return <div className="cardx"><div className="card-head"><b>{title}</b><i className="bi bi-three-dots"/></div><div className="card-body">{children}</div></div>}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export function SelectField({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <Field label={label}><select value={value} onChange={e=>set(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></Field>}
export function Stat({label,value,icon}:{label:string;value:number;icon:string}){return <div className="stat"><div className="stat-icon"><i className={`bi ${icon}`}/></div><div><span>{label}</span><b>{value}</b></div></div>}
export function StatusActions({status,onChange}:{status:string;onChange:(s:string)=>void}){return <div className="status-actions"><span className={`badge ${status.toLowerCase()}`}>{status}</span>{status==='DRAFT'&&<button type="button" onClick={e=>{e.stopPropagation();onChange('REVIEW')}}>Review</button>}{status==='REVIEW'&&<button type="button" onClick={e=>{e.stopPropagation();onChange('APPROVED')}}>Setujui</button>}</div>}
export function DataTable({headers,rows,onRow}:{headers:string[];rows:ReactNode[][];onRow?:(i:number)=>void}){return <div className="table-wrap"><table className="table-bordered"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} onClick={()=>onRow?.(i)} className={onRow?'clickable':''}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">Belum ada data.</td></tr>}</tbody></table></div>}

export function RiskStatusActions({status,onChange,canAuthor,canReview,canApprove}:{status:string;onChange:(s:string)=>void;canAuthor:boolean;canReview:boolean;canApprove:boolean}){return <div className="status-actions"><span className={`badge ${String(status).toLowerCase()}`}>{status}</span>{canAuthor&&(status==='DRAFT'||status==='REJECTED')&&<button type="button" onClick={()=>onChange('SUBMITTED')}>{status==='REJECTED'?'Ajukan Ulang':'Ajukan'}</button>}{canReview&&status==='SUBMITTED'&&<><button type="button" onClick={()=>onChange('REVIEWED')}>Reviu</button><button type="button" onClick={()=>onChange('REJECTED')}>Tolak</button></>}{canApprove&&status==='REVIEWED'&&<><button type="button" onClick={()=>onChange('APPROVED')}>Tetapkan</button><button type="button" onClick={()=>onChange('REJECTED')}>Tolak</button></>}</div>}
